# Generated by Django 4.2.5 on 2023-09-20 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modules',
            name='id_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='id_users', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
    ]
